<!DOCTYPE html>
<html>

	<head>
		<?php $this->partial("components/head") ?>
		<link rel="stylesheet" type="text/css" href="assets/css/core.css" />
	</head>
	<body>
		<?php $this->partial("components/header") ?>
		
		<div class="w-100p bg-white">
			<div class="container text-center">
				<h1>About Us 关于我们</h1>
			</div>
		</div>
		
		<div class="container mt-10">
			<img src="http://usr.im/1200x1000" alt="关于我们" />
		</div>
		<?php $this->partial("components/footer") ?>
	</body>

</html>