<!DOCTYPE html>
<html>

	<head>
		<?php $this->partial("components/head") ?>
		<link rel="stylesheet" type="text/css" href="assets/css/core.css" />
	</head>
	<body>
		<?php $this->partial("components/header") ?>
		
		<div class="w-100p bg-white">
			<div class="container text-center">
				<h1>About Us 关于我们</h1>
			</div>
		</div>
		
		<div class="container mt-10">
			<img src="http://usr.im/1200x1000" alt="关于我们" />
		</div>

		<div class="w-100p bg-dark-orange" style="height:1px"></div>
		<div class="w-100p bg-white">
			<div class="container">
				<ul class="nav nav-fill">
					<li class="nav-item pl-40">
						<i class="iconfont icon-number font-size-46 text-dark-darkturquoise float-left"></i>
						<div style="position: relative;left:5px;top:8px;"><h4>在线找房</h4><small class="font-size-12 text-dark-darkgray">随时拨打客服热线预约看房</small></div>
					</li>
					<li class="nav-item pl-40">
						<i class="iconfont icon-number2 font-size-46 text-dark-darkturquoise float-left"></i>
						<div style="position: relative;left:5px;top:8px;"><h4>管家陪看</h4><small class="font-size-12 text-dark-darkgray">管家全程陪同解除疑惑</small></div>
					</li>
					<li class="nav-item pl-40">
						<i class="iconfont icon-number3 font-size-46 text-dark-darkturquoise float-left"></i>
						<div style="position: relative;left:5px;top:8px;"><h4>签订协议</h4><small class="font-size-12 text-dark-darkgray">了解入住须知抢占优质房源</small></div>
					</li>
					<li class="nav-item pl-40">
						<i class="iconfont icon-number4 font-size-46 text-dark-darkturquoise float-left"></i>
						<div style="position: relative;left:5px;top:8px;"><h4>付款方式</h4><small class="font-size-12 text-dark-darkgray">选择您喜欢的付款方式</small></div>
					</li>
					<li class="nav-item pl-40">
						<i class="iconfont icon-number5 font-size-46 text-dark-darkturquoise float-left"></i>
						<div style="position: relative;left:5px;top:8px;"><h4>拎包入住</h4><small class="font-size-12 text-dark-darkgray">随时随地拎包入住</small></div>
					</li>
				</ul>
			</div>
		</div>
		<?php $this->partial("components/footer") ?>
	</body>

</html>