<!DOCTYPE html>
<html>
	<head>
		<?php $this->partial("components/head") ?>  

		<link rel="stylesheet" type="text/css" href="assets/css/core.css" />
	</head>
	<body>
		<?php $this->partial("components/header") ?>
		
		<div class="w-100p bg-white">
			<div class="container text-center">
				<h1>Join Us 加入我们</h1>
			</div>
		</div>
		
		<div class="container mt-10">
			<div class="join">
				<ul class="join-categories float-left">
					<li class="selected"><a href="javascript:void(0);">房源负责人</a></li>
					<li><a href="javascript:void(0);">平面设计师</a></li>
					<li><a href="javascript:void(0);">在线客服人员</a></li>
					<li><a href="javascript:void(0);">WEB前端开发工程</a></li>
				</ul>
				<div class="join-items float-none">
					<div class="join-content" style="display: block;"><h3>房源负责人</h3><br />
						工作职责：<br />
						1.负责招募、管理房源团队培训、考核各级员工，确保其按照公司的要求和规范开展工作。<br />
						2.负责理顺并优化内部流程，做好与相关部门的衔接和协调工作。<br />
						3.根据市场情况和竞争状态，对公司销售目标进行合理有效分解，完成阶段性目标任务，为整体任务的完成提供有力保障。<br />
						4.策划各类营销活动，为房源开发提供更多的渠道，根据制定相关策略确保销售任务的有效完成。<br />
						<br /><br />
						任职资格：<br /> 
						1.22岁以上，大专及以上学历。<br />
						2.形象端正，有亲和力，擅长倾听。<br />
						3.对销售有强烈的兴趣，对人生充满激情，不断挑战自己。<br />
						4.有强烈的责任心，有耐性，工作积极主动，充满热情。<br />
						5.有良好的解决问题的能力及沟通协调能力。<br />
						6.充满正能量，待人接物态度积极阳光。<br />
						7.有房地产售楼或中介公司经验优先。<br />
						8.薪资面议。<br />
						<br /><br />
						工作地点：广州 ，请将简历投递至Service@52tuanzu.com
					</div>
					<div class="join-content"><h3>平面设计师</h3><br />
						工作职责: <br />
						1.网站界面设计，公司促销等视觉工程的设计制作。 <br /><br />
						
						任职资格： <br />
						1.20-30岁，大专及以上学历。 <br />
						2.熟练操作PS，AI，CDR,等设计软件。 <br />
						3.有较强的设计感觉，并且能够做出打动消费者的作品。 <br />
						4.有强烈的责任感，工作积极主动，热情。 <br /><br />
						
						工作地点：广州 ，请将简历投递至Service@52tuanzu.com
					</div>
					<div class="join-content"><h3>在线客服人员</h3><br />
						工作职责： <br />
						1.负责接受租户网络咨询，解答疑问 。<br /> 
						2.负责协调售后问题分配到相应部门并跟进。 <br />
						3.负责资料的整理和录入。 <br />
						4.负责相关数据的统计和整理。 <br /><br />
						
						任职资格： <br />
						1.20-30岁，大专及以上学历。<br /> 
						2.形象端正, 自信、富有亲和力，有甜美的声音跟良好的普通话发音。<br /> 
						3.熟悉使用各种办公软件。 <br />
						4.有强烈的责任心，有耐性，工作积极主动，充满热情。<br /> 
						5.有良好的解决问题的能力及沟通协调能力。 <br />
						6.充满正能量，待人接物态度积极阳光。 <br />
						7.至少有2年相关工作经验，有大型公司客服工作经验优先。<br /><br />
						
						工作地点：广州 ，请将简历投递至Service@52tuanzu.com
					</div>
					<div class="join-content"><h3>WEB前端开发工程师</h3><br />
						工作职责：<br />
						1.负责网站前端和系统前端功能的开发、调试和维护。<br />
						2.实现产品提出的交互需求，配合后端完成相关API调用。<br />
						3.规范页面代码，优化页面加载性能，提升用户体验。<br />
						4.提出最优的前端技术解决方案，配合完成产品SEO优化。<br /><br />
						
						任职资格：<br />
						1.22-28岁，专科及以上学历，计算机相关专业。<br />
						2.一年以上WEB前端开发经验，有移动设备网站开发经验优先，有中大型项目经验优先。<br />
						3.对WEB标准、易用性、浏览器兼容性有丰富的经验和解决方案。<br />
						4.熟练掌握HTML/CSS/JS开发技术，熟悉HTML5/CSS3新功能，有bs经验优先。<br />
						5.熟练掌握JQUERY等JS框架，并可独立开发组件，有AJAX、Json经验优先。<br />
						6.对前端有浓厚兴趣，平时能关注最新技术发展。<br /><br />
						
						工作地点：广州 ，请将简历投递至Service@52tuanzu.com
					</div>
				</div>
			</div>
		</div>

		<?php $this->partial("components/footer") ?>
		<script type="text/javascript">
			$(document).ready(function() {
				var joinCategories = $('.join-categories'),
					joinContent = $('.join-content');
				joinCategories.on('click', 'li', function(event) {
					event.preventDefault();
					var _this = $(this);
					_this.siblings().removeClass('selected');
					_this.addClass('selected');
					joinContent.siblings().hide();
					joinContent.eq(_this.index()).show();
				});
			});
		</script>
	</body>

</html>