<!DOCTYPE html>
<html>
	<head>
		<?php $this->partial("components/head") ?>
		<link rel="stylesheet" type="text/css" href="assets/css/core.css" />
	</head>
	<body>
		<?php $this->partial("components/header") ?>
		<div class="container mt-10">
			<div class="filter">
				<!--<div class="filter-search clearfix">
					<div class="x4">
						<input type="text" name="" class="form-control" style="display:block;float:left;width: 250px;height:25px;*height:15px;height:15px \0;"/>
						<button class="btn bg-dark-orange text-white" style="width: 80px;height:25px;height:27px \0;line-height:10px;">搜索</button>
					</div>
					<div class="x6" style="line-height: 23px;">
						<a href="javascript:void(0);">华师</a>
						<a href="javascript:void(0);">华师</a>
						<a href="javascript:void(0);">华师</a>
						<a href="javascript:void(0);">华师</a>
					</div>
				</div>-->
				<div class="cb"></div>
				<form id="filterForm" name="form1" method="get" action="/list">
				    <input type="hidden" id="district" name="filter[district]"/>
				    <input type="hidden" id="line" name="filter[line]"/>
			      	<input type="hidden" id="price" name="filter[price]"/>
					<div class="filter-options">
						<dl>
							<dt>区&nbsp;&nbsp;域：</dt>
							<dd class="active"><a href="javascript:void(0);" data-key="district" data-value="0">不限</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="天河区">天河区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="海珠区">海珠区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="越秀区">越秀区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="荔湾区">荔湾区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="白云区">白云区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="黄埔区">黄埔区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="番禺区">番禺区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="南沙区">南沙区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="萝岗区">萝岗区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="花都区">花都区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="增城区">增城区</a></dd>
							<dd><a href="javascript:void(0);" data-key="district" data-value="从化区">从化区</a></dd>
						</dl>
						
						<dl>
							<dt>地&nbsp;&nbsp;铁：</dt>
							<dd class="active"><a href="javascript:void(0);" data-key="line" data-value="0">不限</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="1号线">1号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="2号线">2号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="3号线">3号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="4号线">4号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="5号线">5号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="6号线">6号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="7号线">7号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="8号线">8号线</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="APM">APM</a></dd>
							<dd><a href="javascript:void(0);" data-key="line" data-value="广佛线">广佛线</a></dd>
						</dl>
						
						<dl>
							<dt>租&nbsp;&nbsp;金：</dt>
							<dd class="active"><a href="javascript:void(0);" data-key="price" data-value="0">不限</a></dd>
							<dd><a href="javascript:void(0);" data-key="price" data-value="0-1500">0-1500</a></dd>
							<dd><a href="javascript:void(0);" data-key="price" data-value="1500-2000">1500-2000</a></dd>
							<dd><a href="javascript:void(0);" data-key="price" data-value="2000-2500">2000-2500</a></dd>
							<dd><a href="javascript:void(0);" data-key="price" data-value="2500-3000">2500-3000</a></dd>
							<dd><a href="javascript:void(0);" data-key="price" data-value="3000-5000">3000-5000</a></dd>
						</dl>

						<!--<dl>
							<dt>室&nbsp;&nbsp;友：</dt>
							<dd class="active"><a href="javascript:void(0);">不限</a></dd>
							<dd><a href="javascript:void(0);">女神</a></dd>
							<dd><a href="javascript:void(0);">男神</a></dd>
						</dl>-->

						<!--<dl>
							<dt>配&nbsp;&nbsp;置：</dt>
							<dd><a href="javascript:void(0);">独立卫生间</a></dd>
							<dd><a href="javascript:void(0);">带阳台</a></dd>
							<dd><a href="javascript:void(0);">带飘窗</a></dd>
							<dd><a href="javascript:void(0);">可住俩人</a></dd>
						</dl>-->
					</div>
				</form>
			</div>
		</div>

		<div class="container mt-10">
			<div class="filter">
				<ul class="nav">
					<li class="nav-item"><a class="nav-link-sm text-dark-orange" href="javascript:void(0);">默认</a></li>
					<!--<li class="nav-item"><a class="nav-link-sm text-dark-darkgray" href="javascript:void(0);">价格低~高</a></li>
					<li class="nav-item"><a class="nav-link-sm text-dark-darkgray" href="javascript:void(0);">价格高~低</a></li>-->
				</ul>
			</div>
		</div>

		<div class="container">
			<?php foreach($page->items as $k => $v) { ?>
				<?php if($k % 4 == 0) { ?>
					<?= '<div class="line-big">' ?>
				<?php } ?>
				<div class="x3">
					<div class="item">
						<div class="item-header clearfix">
							<h3><a href="/room/<?=$v->number?>/<?=chr($v->tab)?>_<?=$v->id?>.html" target="_blank"><?=$v->title?>-<?=chr($v->tab)?>房</a></h3><span class="favorite"><i class="iconfont icon-heart"></i><?=$v->id?></span></div>
						<div class="item-img">
							<a href="/room/<?=$v->number?>/<?=chr($v->tab)?>_<?=$v->id?>.html" target="_blank"><img src="<?=$v->titlepic?>" alt="<?=$v->title?>-<?=chr($v->tab)?>房"><span class="rent">出租</span></a>
						</div>
						<div class="item-detail">
							<div class="float-left"><span>地址:<?=$v->street?></span></div>
							<div class="float-right"><span class="price"><?=$v->price?>元/月</span></div>
						</div>
					</div>
				</div>
				<?php if($k % 4 == 3) { ?>
					<?= '</div>' ?>
				<?php } ?>
			<?php } ?>
		</div>
		
		<div class="container mt-10">
			<div class="filter">
				<ul class="nav mlr-a">
					<?php
						if(strpos($_SERVER['REQUEST_URI'], '&p=')) {
							$href = explode('&p=', $_SERVER['REQUEST_URI']);
						} else {
							$href = explode('?p=', $_SERVER['REQUEST_URI']);
						}
					?>
					<?=$page -> current == 1?'':'<li class="nav-item"><a class="nav-link text-dark-darkgray" href="' . $href[0] . '&p=' . $page -> first . '">首页</a></li>'?>
					<?=$page -> current == 1?'':'<li class="nav-item"><a class="nav-link text-dark-darkgray" href="' . $href[0] . '&p=' . $page -> before . '">上一页</a></li>'?>
					<?php
						$maxSize = 6;
						$startPage = 1;
						$endPage = $page->total_pages;
						$startPage = max($page->current - floor($maxSize / 2),1);
						$endPage = min($startPage + $maxSize - 1, $page->total_pages);
						for($i=$startPage;$i<=$endPage;$i++) {
					?>
						<?php if($page->current == $i) { ?>
							<li class="nav-item"><a class="nav-link text-dark-orange" href="javascript:void(0);"><?=$i?></a></li>
						<?php } else {?>
							<li class="nav-item"><a class="nav-link text-dark-darkgray" href="<?=$href[0]?>&p=<?=$i?>"><?=$i?></a></li>
						<?php } ?>
					<?php } ?>
					<?=$page -> current == $page -> total_pages?'':'<li class="nav-item"><a class="nav-link text-dark-darkgray" href="' . $href[0] . '&p=' . $page -> next . '">下一页</a></li>'?>
					<?=$page -> current == $page -> total_pages?'':'<li class="nav-item"><a class="nav-link text-dark-darkgray" href="' . $href[0] . '&p=' . $page -> last . '">尾页</a></li>'?>
				</ul>
			</div>
		</div>
		
		<?php $this->partial("components/footer") ?>
		<script type="text/javascript">
			var obj = <?= $obj ?>;
		</script>
		<script type="text/javascript" charset="utf-8" src="assets/js/list.js"></script>
	</body>

</html>